name: Python CI

on:
  - push
  - pull_request


jobs:

  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          make install
          make migrate
        env:
          DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb

      - name: Run linter and pytest
        run: |
          make check
        env:
          DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Run test coverage
        run: |
          make test-coverage
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=hexlet-boilerplates_python-package
            -Dsonar.organization=hexlet-boilerplates
            -Dsonar.python.coverage.reportPaths=coverage.xml