name: Python CI

on:
  - push
  - pull_request


jobs:

  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install poetry
          make install
          make migrate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mydb

      - name: Run linter and pytest
        run: |
          make check
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mydb
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

  sonarqube:
    name: SonarQube Cloud
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox

      - name: Install dependencies
        run: |
          pip install poetry
          make install
          make migrate
          make shell
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mydb

      - name: Run tox
        run: tox -e py
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mydb
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}